send_period_milis: 1900
debug:
  default:
    offset: 0
    text: "This text must start at the screen center"
    font:
      id: "minecraft:default"
    alignment: "left"
  test:
    offset: -10
    text: "Some text"
    font:
      id: "minecraft:default"
      height: 8
    alignment: "right"