name: GUIAPI
version: 1.0-alpha.1
main: com.sentropic.guiapi.GUIAPI
api-version: 1.16
depend: [ProtocolLib]
authors: [Sentropic]
commands:
  guiapi:
    description: Main plugin command
    usage: /guiapi reload
    permission: guiapi.command.reload