name: GUIAPI
version: ${project.version}
main: com.sentropic.guiapi.GUIAPI
api-version: 1.16
softdepend: [ProtocolLib]
authors: [Sentropic]
commands:
  guiapi:
    description: Main plugin command
    usage: /guiapi reload, /guiapi debug
    permission: guiapi.command.reload, guiapi.command.debug