name: GUIAPI
version: ${project.version}
main: com.sentropic.guiapi.GUIAPI
api-version: 1.16
softdepend: [ProtocolLib]
authors: [Sentropic]
commands:
  guiapi:
    description: Main plugin command
    usage: /guiapi reload, /guiapi debug
    permission: guiapi.command
permissions:
  guiapi.command:
    description: Gives access to /guiapi command
    default: false